# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LQDNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LQDNews

pod 'Cache’
pod 'Alamofire’
pod 'AlamofireNetworkActivityIndicator’
pod 'XCGLogger’
pod 'Swinject’
pod 'ReachabilitySwift’
pod 'Kingfisher’
pod 'FTLinearActivityIndicator’
pod 'KMNavigationBarTransition’
pod 'Loaf’

end
